---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
