---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns01-staging
  namespace: monitoring
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: marinyuk.dima@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-dns01-key-pair
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z0713262I2BPWP4RABNY
